CREATE TABLE "EmailDailyQuota" (
  "dateKey" TEXT NOT NULL PRIMARY KEY,
  "sendCount" INTEGER NOT NULL DEFAULT 0,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL
);
