"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function VerifyEmailForm({ maskedEmail, hasPending }: { maskedEmail: string | null; hasPending: boolean }) {
  const [code, setCode] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [resending, setResending] = useState(false); const [cooldown, setCooldown] = useState(0);
  useEffect(() => { if (!cooldown) return; const timer = window.setInterval(() => setCooldown((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [cooldown]);
  async function verify(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); const response = await fetch("/api/auth/verify-email", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(data.error ?? "確認できませんでした"); setBusy(false); return; } window.location.assign(typeof data.next === "string" ? data.next : "/onboarding/course"); }
  async function resend() { setResending(true); setError(""); const response = await fetch("/api/auth/resend-verification", { method: "POST" }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(data.error ?? "再送できませんでした"); const retry = Number(response.headers.get("Retry-After")); if (Number.isFinite(retry)) setCooldown(retry); } else setCooldown(60); setResending(false); }
  return <div className="verifyPanel">{hasPending ? <><p>入力されたメールアドレスへ6桁の確認コードを送信しました。</p>{maskedEmail && <p className="mutedText">送信先：{maskedEmail}</p>}<p className="mutedText">コードの有効期限は10分です。</p><form onSubmit={verify}><label className="fieldLabel">確認コード<input className="textInput verifyCodeInput" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} /></label>{error && <p className="formError" role="alert">{error}</p>}<button className="button primaryButton fullButton" disabled={busy || code.length !== 6}>{busy ? "確認中..." : "メールアドレスを確認"}</button></form><button className="button secondaryButton fullButton" disabled={resending || cooldown > 0} onClick={resend}>{cooldown > 0 ? `${cooldown}秒後に再送できます` : resending ? "送信中..." : "確認コードを再送"}</button></> : <><p role="alert">登録情報が見つかりません。登録をやり直してください。</p><Link className="button primaryButton fullButton" href="/signup">登録をやり直す</Link></>}<p className="authSwitch"><Link href="/login">ログイン画面へ</Link></p></div>;
}
